### ISSUE TITLE
I can't find a way to customize or translate the followup that sends the link

### ISSUE THREAD

**Issue by glorenzutti** [ticgal/one-timesecret#10]
<p><a href="https://github.com/ticgal/one-timesecret/issues/10">https://github.com/ticgal/one-timesecret/issues/10</a></p><p>I found the locales dir. But even using one of the default translations, like es_ES, I keep getting the same default message in English.</p><p>Maybe im doing something wrong.</p><p>On the same page, it would be awesome to be able to fully edit the message, per language, directly from the glpi interface. The same way you can customize every notification.</p><p><br />Created by glorenzutti</p>
<blockquote>Numero de la peticion de GLPI: <a href='https://xes.ticgal.com/index.php?redirect=ticket_8309' rel='nofollow'>8309</a><br/>Creado por <a href='https://tic.gal'>GitSync</a> en GLPI por Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi,

If you translate the message in es_ES you will only notice when the other actor (requester or tech) uses this language.
So if you as a tech are using English as default language, and the requester is using Italian, the message will be in Italian.

By the way, you could help us by translating it into Italian if you have the knowledge :) https://localazy.com/p/one-time-secret-glpi#translations

I agree a custom message will be a great improvement but right now it is not in the roadmap. We wanted to keep it both useful and simple. Of course, you can always contribute to the code with a PR or sponsor the feature.

Regards,

**Comment by glorenzutti** [comment]
I can help on es_AR or es_ES or even english. I don't speak Italian. I will ask my kid if he wants to help us out for the Italian.

Thank you!

**Comment by OscarBeiro** [comment]
Any help is welcome :)
