### ISSUE TITLE
When you are behind a corporate proxy, the app dosent use the proxy setup of the glpi app

### ISSUE THREAD

**Issue by glorenzutti** [ticgal/one-timesecret#11]
<p><a href="https://github.com/ticgal/one-timesecret/issues/11">https://github.com/ticgal/one-timesecret/issues/11</a></p><p>I have proxy configured in glpi, and it works. I can download updates, I can install plugins from the market, among other things.</p><p>n</p><p>However, the onetimesecret plugin does not seem to use the proxy settings to make the connection to the onetimesecret.com site to interact with the api.</p><p>n</p><p>This is the log on the glpi:</p><p>n</p><p>*** PHP Warning (2): curl_getinfo(): supplied resource is not a valid cURL handle resource in /var/www/glpi/marketplace/onetimesecret/inc/secret.class.php at line 102nBacktrace :nmarketplace/onetimesecret/inc/secret.class.php:102 curl_getinfo()nmarketplace/onetimesecret/front/link.form.php:39 PluginOnetimesecretSecret::createSecret()</p><p><br />Created by glorenzutti</p>
<blockquote>Numero de la peticion de GLPI: <a href='https://xes.ticgal.com/index.php?redirect=ticket_8311' rel='nofollow'>8311</a><br/>Creado por <a href='https://tic.gal'>GitSync</a> en GLPI por Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi,
You are right, we have not considered this scenario.
We will give it a try when we review the plugin to update it to GLPI 10.
Regards,

**Comment by inesmv** [comment]
Hi!
I modified the code to use a proxy with curl requests if it's configured at GLPI.
Waiting for your reply
Regards,
