### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by boscorelly** [ticgal/one-timesecret#15]
Hi,

maybe it's the same issue as in #11

i can't get the url plugin to work.

`Error:
Warning: curl_getinfo(): supplied resource is not a valid cURL handle resource in D:\xampp-7-4-14\htdocs\glpi\marketplace\onetimesecret\inc\secret.class.php on line 102

Notice: Trying to access array offset on value of type null in D:\xampp-7-4-14\htdocs\glpi\marketplace\onetimesecret\inc\secret.class.php on line 106

Notice: Undefined variable: lang in D:\xampp-7-4-14\htdocs\glpi\marketplace\onetimesecret\inc\secret.class.php on line 180

Notice: Undefined variable: lang in D:\xampp-7-4-14\htdocs\glpi\marketplace\onetimesecret\inc\secret.class.php on line 181

Notice: Undefined variable: lang in D:\xampp-7-4-14\htdocs\glpi\marketplace\onetimesecret\inc\secret.class.php on line 182

Notice: Undefined index: itemtype in D:\xampp-7-4-14\htdocs\glpi\inc\itilfollowup.class.php on line 338`

architecture is :
glpi server <> reverse proxy iis <> firewall <> internet

**Comment by boscorelly** [comment]
`# curl -u "_user_:_key_" https://ots._domaine_.fr/api/v1/status`
`{"status":"nominal","locale":"en"}`

**Comment by boscorelly** [comment]
ok i found the issue : the http protocol is hardcoded. In consequence, adding https in server url break it.

**Comment by OscarBeiro** [comment]
Hi,
We are trying to send sensitive information securely. I think we can both agree using http is not a good idea :)
Cheers,

**Comment by boscorelly** [comment]
Yes but http(s):// must be stripped from post
    	
    
  

 De : Oscar B. ***@***.***>Envoyé : jeudi, février 24, 2022 3:16 PMÀ : ticgal/one-timesecretCc : Camille Ollié; State changeObjet : Re: [ticgal/one-timesecret] Plugin not working (Issue #15) 
Hi,
We are trying to send sensitive information securely. I think we can both agree using http is not a good idea :)
Cheers,

**Comment by OscarBeiro** [comment]
It 
Call me lazy, but it will be easier to change the string to add this information :)
