### ISSUE TITLE
GLPI plugin - How to generate random password directly?

### ISSUE THREAD

**Issue by dlecleire** [ticgal/one-timesecret#33]
Hi,
I added One-TimeSecret plugin in GLPI and I would generate random password directly in GLPI.
Is-it possible ?

**Comment by OscarBeiro** [comment]
Hi,
We appreciate your suggestion.
This is not an objective for One-TimeSecret.
It is a good idea to generate a random password, but you still need to add it to the system and document it.
Unfortunately, none of these is on the roadmap currently. 
We are working in another plugin to manage passwords which should integrate with OTS in the future.
Regards,
