### ISSUE TITLE
Add Catalan language

### ISSUE THREAD

**Issue by tmayans** [ticgal/one-timesecret#34]
Hello,
I've added the language catalan (CA and ca_ES) to localazy but meanwhile is approved and included in future releases, I'm trying to install it manually in our server.
I've created the .po and .mo files, review the permissions to www-data, restart apache service, but the text appears in English.
Can you add the language to the plugin or explain if I'm doing some wrong step to apply in my installation?

Thank you very much.

**Comment by tmayans** [comment]
Finally, clearing GLPI cache has applied the changes. The files of Catalan language are available in Localazy pending to review.
I hope we see the catalan option in future releases.

Thank you.

**Comment by OscarBeiro** [comment]
Sure. 
Moltes gràcies ;)
