### ISSUE TITLE
Blank passwords

### ISSUE THREAD

**Issue by Jyru-Ken** [ticgal/one-timesecret#35]
Hello and thanks for this code ;)

It works like a charm when i fill up all the fields required on a GLPI Followup, but if i don't fill a password, it doesn't work. 

The link is just "https://onetimesecret.com/secret/" and is not correctly generated. If i do the qame on the OTS web site, i can choose to not set a password.

Could you have a look please ?  

Thanks & best regards

PS : i do the trick for having the alert for blank password but i would know if it possible to have the choice (blank password or not)

**Comment by OscarBeiro** [comment]
Hi,
We use this plugin daily and don't have this issue.
Are you using the last GLPI and Plugin version?
Regards,
