### ISSUE TITLE
Problems parsing JSON

### ISSUE THREAD

**Issue by gitsyncuser** [ticgal/one-timesecret#39]
<p>The plugin and link work correctly but this message appears:<br><br>{ \"message\": \"Problems parsing JSON\", \"documentation_url\": \"https://docs.github.com/rest/issues/comments#create-an-issue-comment\" }</p>\n<p><a href=\"https://xes.ticgal.com/front/document.send.php?docid=44228&amp;itemtype=Ticket&amp;items_id=16518\" target=\"_blank\" rel=\"noopener\"><img src=\"https://xes.ticgal.com/front/document.send.php?docid=44228&amp;itemtype=Ticket&amp;items_id=16518\" alt=\"10a52905-e509fb39-64b7e45e48d588.83041693\" width=\"541\"></a></p><blockquote>Numero de la peticion de GLPI: <a href='https://xes.ticgal.com/index.php?redirect=ticket_16521' rel='nofollow'>16521</a><br>Creado por <a href='https://tic.gal'>GitSync</a> en GLPI por Daniel Couso</blockquote>

**Comment by OscarBeiro** [comment]
It should be fixed on 2.0.3.
Regards
