### ISSUE TITLE
onetimesecret.com hardcoded

### ISSUE THREAD

**Issue by vemi2709** [ticgal/one-timesecret#4]
<p><a href="https://github.com/ticgal/one-timesecret/issues/4">https://github.com/ticgal/one-timesecret/issues/4</a></p><p>Hi, seems like onetimesecret.com is hardcoded in secret.class.php, we can't use our own One-Time Secret installation. -VeM-</p><p><br />Created by vemi2709</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_7780' rel='nofollow'>7780</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
You are right. Thanks for reporting it.

**Comment by OscarBeiro** [comment]
Could you please confirm that this patch fixes the issue?
https://github.com/ticgal/one-timesecret/commit/a4d7256fddbe609e1a01650f188343bc66b2447d
Thanks

**Comment by vemi2709** [comment]
There must be something wrong with our own installation, the plugin works now when we use onetimesecret.com as the address.
We investigate the matter a little bit more.

**Comment by vemi2709** [comment]
Now it works, it was once again about certificates :)

**Comment by OscarBeiro** [comment]
Yep, we had that same issue with the onetimesecret.com. Certificates can be tricky.
Thanks for the feedback.
