### ISSUE TITLE
Backslash added when creating a OTS with apostrophe or quotation mark

### ISSUE THREAD

**Issue by blublu31** [ticgal/one-timesecret#44]
Hello,

There is a problem when creating a OneTimeSecret with GLPI, it creates a backslash when using an apostrophe or a quotation mark.

Here is an exemple : 

![Test1](https://github.com/ticgal/one-timesecret/assets/59641773/b59a094e-b24e-4c2f-9b68-bf6d7c1cbaad)
![Test2](https://github.com/ticgal/one-timesecret/assets/59641773/65692067-c42a-4f36-a4be-10b7bd714f18)

**Comment by OscarBeiro** [comment]
Please update and report back if necessary.

**Comment by blublu31** [comment]
Hello,
I have updated to 2.1.1 and still have the issue.
![image](https://github.com/ticgal/one-timesecret/assets/59641773/97d70c38-5326-4c61-9849-981729e39479)

**Comment by OscarBeiro** [comment]
We are studying a workaround or a fix.
I'll let you know.

**Comment by OscarBeiro** [comment]
Could you please test the last version and report back?
https://github.com/ticgal/one-timesecret/releases/tag/2.1.2
