### ISSUE TITLE
Something wrong happened

### ISSUE THREAD

**Issue by Hantiel** [ticgal/one-timesecret#47]
Hi.

As of today - 16.04.2024. the ability to add passwords via the OTS has stopped working. The message "Something wrong happened" is displayed.
The problem occurred on 3 servers - with GLPI versions 10.0.11 / 10.0.14 and plugin version - 2.1.1 / 2.0.0.

Please verify if anyone else is having this problem and it is a plugin error / vendor issue (OTS) or something has screwed up on my servers. 
Thanks in advance for your help :)

![image](https://github.com/ticgal/one-timesecret/assets/113474035/057c5e6f-870e-4364-b226-8046104458f4)

**Comment by OscarBeiro** [comment]
We use it daily and it's working fine.
Probably something on your end.
Regards,
