### ISSUE TITLE
Wrong asset name

### ISSUE THREAD

**Issue by fluchtkapsel** [ticgal/one-timesecret#48]
When trying to update, GLPI complains about being unable to download the archive. Some investigation later I could find out that the asset is called `onetimesecret-2.1.3.tar.tgz` but the marketplace metadata advertises `glpi-onetimesecret-2.1.3.tar.tgz`

**Comment by OscarBeiro** [comment]
Thanks for the report.
A common mistake :) It's fixed now.
Regards,
