### ISSUE TITLE
Incident in progress? 

### ISSUE THREAD

**Issue by Sp4m4** [ticgal/one-timesecret#50]
Hello, 

GLPI Plugin returns error 'something goes wrong' and Error 503 appears on https://onetimesecret.com/

Thanks a lot !

**Comment by OscarBeiro** [comment]
Hi,
This is a One Time Secret website issue, not the plugin's.
![image](https://github.com/user-attachments/assets/485dad52-5c2f-4ff6-b6b5-16fc88cfa769)

You can host your version of the application and report to the owners.
Regards,

**Comment by delano** [comment]
@Sp4m4 The service is back up now. Thanks for the report.
