### ISSUE TITLE
Custom email/follow-up

### ISSUE THREAD

**Issue by jcervantes-sipecom** [ticgal/one-timesecret#6]
In the page about this new plugin (https://tic.gal/en/project/onetimesecret/) says: "You can tailor the follow-up to your needs by altering the translations files."

How can I do that? I try to find the notification and template for this but I couldn't find anything.

**Comment by OscarBeiro** [comment]
Hi,
This is not a different item, but an automated Follow-up.
The best way is by altering the translation files to suit your needs, either by editing native ones, bearing in mind, they will be overwritten on plugin update. 
Regards,
