### ISSUE TITLE
Integración con el plugin accounts

### ISSUE THREAD

**Issue by jbonor** [ticgal/one-timesecret#7]
<p><a href="https://github.com/ticgal/one-timesecret/issues/7">https://github.com/ticgal/one-timesecret/issues/7</a></p><p>Muy útil este plugin, me pregunto si sería posible integrar este plugin con el de accounts para poder compartir las contraseñas ahí guardadas?</p><p><br />Created by jbonor</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_7862' rel='nofollow'>7862</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Hi Jorge,
Please use English to help us reach a wider audience :)

It looks like a pretty good idea. We are using [@Accounts](https://github.com/InfotelGLPI/accounts) although it lacks some restriction functionalities.

You have two choices here:
1. Build yourself the integration and send a PR
2. Ask for a proposal :)

Regards,
